hospital/urls.py
from django.urls import path
from.import views

app_name ="hospital"

urlpatterns = [
    path('',views.index,name="index"),
    path('about',views.about,name="about"),
    path('contact',views.contact,name="contact"),
    path('appointment',views.appointment,name="appointment"),
    path('doctorprofile',views.doctorprofile,name="doctorprofile"),
    path('single',views.single,name="single"),
    path('gallery',views.gallery,name="gallery"),
    path('staffprofile',views.staffprofile,name="staffprofile"),
    path('user_register', views.user_register, name="user_register"),
    path('user_login', views.user_login, name="user_login"),
    path('user_logout', views.user_logout, name="user_logout"),
    path('user_welcome', views.user_welcome, name="user_welcome"),
    path('profile', views.profile, name="profile"),
    path('doctor1', views.doctor1, name="doctor1"),
    path('doctor2', views.doctor2, name="doctor2"),
    path('doctor3', views.doctor3, name="doctor3"),
    path('doctor4', views.doctor4, name="doctor4"),
    path('doctor5', views.doctor5, name="doctor5"),
    path('doctor6', views.doctor6, name="doctor6"),
    path('doctor7', views.doctor7, name="doctor7"),
    path('doctor8', views.doctor8, name="doctor8"),
    path('doctor9', views.doctor9, name="doctor9"),
    path('doctor10', views.doctor10, name="doctor10"),
    path('doctor11', views.doctor11, name="doctor11"),
    path('doctor12', views.doctor12, name="doctor12"),
    path('doctor13', views.doctor13, name="doctor13"),
    path('doctor14', views.doctor14, name="doctor14"),
    path('patientform', views.patientform, name="patientform"),
    path('auth', views.auth, name="auth"),
    path('authL', views.authL, name="authL"),
    path('authR', views.authR, name="authR"),
    path('thankyou', views.thankyou, name="thankyou"),
]

untitled3/urls.py
from typing import List, Any

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospital.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospital/models.py
from django.db import models
from django.contrib.auth.models import User

class UserRole(models.Model):
    CHOICES = (
        ('p', 'patient'),
        ('s', 'staff'),
        ('d', 'doctor'),

    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=200,choices=CHOICES,default='p')


    def __str__(self):
        return self.role


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    mobile = models.CharField(max_length=200)
    image = models.FileField(upload_to='user_image')
    fileno = models.CharField(max_length=200 , default="")
    age = models.CharField(max_length=200, default="")
    dob = models.CharField(max_length=200, default="")
    issue = models.CharField(max_length=200, default="")
    pastissue= models.CharField(max_length=200, default="")
    prescription= models.CharField(max_length=200, default="")

    bill = models.FileField(upload_to='user_image', default="")

    def __str__(self):
        return self.user.username
# class StaffProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     address = models.CharField(max_length=255)
#
#     image = models.FileField(upload_to='user_image')
#     sid = models.CharField(max_length=200, default="")
#     age = models.CharField(max_length=200, default="")
#     dob = models.CharField(max_length=200, default="")
#     department = models.CharField(max_length=200, default="")
#     qualification = models.CharField(max_length=200, default="")
#     designation = models.CharField(max_length=200, default="")
#     number = models.CharField(max_length=200, default="")
#
#     def __str__(self):
#         return self.user.username
# class DoctorProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     address = models.CharField(max_length=255)
#
#     image = models.FileField(upload_to='user_image')
#     experience1 = models.CharField(max_length=200, default="")
#     experience2 = models.CharField(max_length=200, default="")
#     experience3 = models.CharField(max_length=200, default="")
#     # experience4 = models.CharField(max_length=200, default="")
#     # experience5 = models.CharField(max_length=200, default="")
#     # age = models.CharField(max_length=200, default="")
#     # dob = models.CharField(max_length=200, default="")
#     department = models.CharField(max_length=200, default="")
#     qualification1 = models.CharField(max_length=500, default="")
#     qualification2 = models.CharField(max_length=500, default="")
#     qualification3 = models.CharField(max_length=500, default="")
#     # qualification4 = models.CharField(max_length=500, default="")
#     designation = models.CharField(max_length=200, default="")
#     number = models.CharField(max_length=200, default="")
#
#     def __str__(self):
#         return self.user.username

class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default="")
    email = models.CharField(max_length=200, default="")
    number = models.CharField(max_length=200, default="")
    fileno = models.CharField(max_length=10, default="")

    doa = models.CharField(max_length=200, default="")
    cdoctor = models.CharField(max_length=200, default="")
    timetable = models.CharField(max_length=200, default="")
    def __str__(self):
        return self.user.username


class Contact(models.Model):
    name = models.CharField(max_length=200, default="")
    email = models.CharField(max_length=200, default="")
    subject = models.CharField(max_length=200, default="")
    message = models.CharField(max_length=10, default="")
    def __str__(self):
        return self.name

hospital/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect , HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from .models import Profile, Appointment, Contact
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    return render(request, 'hospital/index.html')


def about(request):
    return render(request, 'hospital/about.html')


def appointment(request):
    return render(request, 'hospital/appointment.html')


def contact(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')
        contactus = Contact(name=name , email=email , subject=subject , message=message )
        contactus.save()

    return render(request, 'hospital/contact.html',{"data1":"data1"})



def doctorprofile(request):
    return render(request, 'hospital/doctorprofile.html')


def single(request):
    return render(request, 'hospital/single.html')

def doctor1(request):
    return render(request, 'hospital/doctor1.html')

def doctor2(request):
    return render(request, 'hospital/doctor2.html')

def doctor3(request):
    return render(request, 'hospital/doctor3.html')

def doctor4(request):
    return render(request, 'hospital/doctor4.html')

def doctor5(request):
    return render(request, 'hospital/doctor5.html')

def doctor6(request):
    return render(request, 'hospital/doctor6.html')

def doctor7(request):
    return render(request, 'hospital/doctor7.html')

def doctor8(request):
    return render(request, 'hospital/doctor8.html')

def doctor9(request):
    return render(request, 'hospital/doctor9.html')

def doctor10(request):
    return render(request, 'hospital/doctor10.html')

def doctor11(request):
    return render(request, 'hospital/doctor11.html')

def doctor12(request):
    return render(request, 'hospital/doctor12.html')

def doctor13(request):
    return render(request, 'hospital/doctor13.html')

def doctor14(request):
    return render(request, 'hospital/doctor14.html')

def gallery(request):
    return render(request, 'hospital/gallery.html')


def staffprofile(request):
    return render(request, 'hospital/staffprofile.html')

def profile(request):
    return render(request, 'hospital/profile.html')

def pateintform(request):
    return render(request, 'hospital/patientform.html')

def auth(request):
    return render(request, 'hospital/auth.html')

def authL(request):
    return render(request, 'hospital/authL.html')

def authR(request):
    return render(request, 'hospital/authR.html')

def thankyou(request):
    return render(request, 'hospital/thankyou.html')



def user_register(request):
    if request.method == "POST":
        username = request.POST.get("username" ,"")
        email= request.POST.get("email" ,"")
        password = request.POST.get("password" ,"")
        if  User.objects.filter(username=username).exists() is not True \
                or User.objects.filter(email=email).exists() is not True:
            User.objects.create_user(username,email,password)
            return HttpResponseRedirect(reverse('hospital:index'))
        else:
            msg = {'msg' : "user already exists"}
        return render(request, 'hospital/authR.html', msg)

    else:
        return render(request,'hospital/index.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username' , '')
        password = request.POST.get('password' , "")
        user = authenticate(username=username,password=password)
        print(user)
        if user is not None:
              login(request,user)
              return HttpResponseRedirect(reverse('hospital:index'))

        else:
            msg = {'msg' : "wrong email or password"}
            return  render(request, 'hospital/authL.html', msg)
        return  HttpResponseRedirect(reverse('hospital:index'))
    else:
        return render(request,'hospital/index.html')

def user_welcome(request):
    return render(request,'hospital/index.html')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('hospital:index'))

def patientform(request):
    if request.method == "POST":
        address = request.POST.get('address' , '')
        mobile = request.POST.get('mobile' , '')
        image = request.FILES.get('image','')
        fileno = request.POST.get('fileno','')
        dob = request.POST.get('dob','')
        age = request.POST.get('age','')
        issue = request.POST.get('issue','')
        pastissue = request.POST.get('pastissue','')

        prescription = request.POST.get('prescription','')
        bill = request.FILES.get('bill','')
        user = request.user
        profile = Profile(user=user , address=address , mobile=mobile , image=image ,fileno=fileno, dob=dob , age=age ,issue=issue ,prescription=prescription  ,pastissue=pastissue ,  bill=bill)
        profile.save()
        userProfile = Profile.objects.get(user=user)
        return render(request, 'hospital/patientform.html' , {'profile' :userProfile})

    else:
        try:
            user =  request.user
            userProfile = Profile.objects.get(user=user)
            return render(request, 'hospital/patientform.html', {'profile': userProfile})
        except:
            return render(request , 'hospital/patientform.html')

def update_patient_profile(request):
    if request.method == "POST":
        user = request.user
        profile = Profile.objects.get(user=user)
        address = request.POST.get('address', '')
        mobile = request.POST.get('mobile', '')
        image = request.FILES.get('image', '')
        fileno = request.POST.get('fileno','')
        dob = request.POST.get('dob', '')
        age = request.POST.get('age','')
        issue = request.POST.get('issue', '')
        pastissue = request.POST.get('pastissue', '')
        prescription = request.POST.get('prescription', '')
        bill = request.FILES.get('bill', '')
        profile.address = address
        profile.mobile = mobile
        profile.image = image
        profile.fileno=fileno
        profile.age=age
        profile.dob=dob
        profile.issue=issue
        profile.prescription=prescription
        profile.pastissue=pastissue
        profile.bill=bill
        print(profile)
        profile.save()

        userProfile = Profile.objects.get(user=user)
        return render(request, 'hospital/patientform.html', {'profile': userProfile})
    else:
        return HttpResponseRedirect(reverse('hospital:index'))


# def staffform(request):
#     if request.method=='POST':
#         address = request.POST.get('address', '')
#         image = request.FILES.get('image', '')
#         sid = request.POST.get('sid', '')
#         dob = request.POST.get('dob', '')
#         age = request.POST.get('age', '')
#         designation = request.POST.get('designation', '')
#         department = request.POST.get('department', '')
#         number = request.POST.get('number', '')
#         qualification = request.POST.get('qualification', '')
#
#         user = request.user
#         staff = StaffProfile(user=user, address=address, image=image, sid=sid, dob=dob, age=age,
#                           designation=designation , department=department, qualification=qualification, number=number)
#         staff.save()
#         staffNewProfile = StaffProfile.objects.get(user=user)
#         return render(request, 'hospital/staffform.html', {'profile': staffNewProfile})
#
#     else:
#         try:
#             user = request.user
#             print(user)
#             staff = StaffProfile.objects.get(user=user)
#             print("---",staff.sid)
#             msg = {"profileStaff":staff}
#             print(msg)
#             return render(request , 'hospital/staffform.html' ,msg)
#         except Exception as e:
#             print(e)
#             return render(request, 'hospital/staffform.html')
#
#
# def update_staff_profile(request):
#     if request.method == "POST":
#         user = request.user
#         staff = StaffProfile.objects.get(user=user)
#         address = request.POST.get('address', '')
#
#         image = request.FILES.get('image', '')
#         sid = request.POST.get('sid', '')
#         dob = request.POST.get('dob', '')
#         age = request.POST.get('age', '')
#         designation = request.POST.get('designation', '')
#         department = request.POST.get('department', '')
#         number = request.POST.get('number', '')
#         qualification = request.POST.get('qualification', '')
#         staff.address = address
#
#         staff.image = image
#         staff.sid = sid
#         staff.age = age
#         staff.dob = dob
#         staff.designation = designation
#         staff.department = department
#         staff.number = number
#         staff.qualification = qualification
#
#         print(staff)
#         staff.save()
#
#         staff = StaffProfile.objects.get(user=user)
#         return render(request, 'hospital/staffform.html', {'staffprofile': staff})
#     else:
#         return HttpResponseRedirect(reverse('hospital:index'))
#
# def doctorform(request):
#     if request.method=='POST':
#         address = request.POST.get('address', '')
#         image = request.FILES.get('image', '')
#
#         dob = request.POST.get('dob', '')
#         age = request.POST.get('age', '')
#         designation = request.POST.get('designation', '')
#         department = request.POST.get('department', '')
#         number = request.POST.get('number', '')
#         qualification1 = request.POST.get('qualification1', '')
#         qualification2 = request.POST.get('qualification2', '')
#         qualification3 = request.POST.get('qualification3', '')
#         qualification4 = request.POST.get('qualification4', '')

hospital/templates/hospital/auth.html
{% extends 'hospital/base.html' %}
{% load static %}
{% block body %}

   <!-- banner 2 -->
   <div class="inner-banner-w3ls">
      <div class="container">

      </div>
   </div>

   <!-- authentication error -->
   <div class="appointment py-5">
      <div class="py-xl-5 py-lg-3">
         <div class="w3ls-titles text-center mb-5">
            <h3 class="title">login Error</h3>
            <span>
               <i class="fas fa-user-md"></i>
            </span>
             <h5 class="mt-2">Please Make Sure You Login First</h5>
            </div>
            <div class="clerafix"></div>
         </div>
      </div>
   </div>
   <!-- authentication error -->
{% endblock %}

hospital/templates/hospital/authR.html
{% extends 'hospital/base.html' %}
{% load static %}
{% block body %}

   <!-- banner 2 -->
   <div class="inner-banner-w3ls">
      <div class="container">

      </div>
   </div>

   <!-- authentication error -->
   <div class="appointment py-5">
      <div class="py-xl-5 py-lg-3">
         <div class="w3ls-titles text-center mb-5">
            <h3 class="title">User Alredy Exists</h3>
            <span>
               <i class="fas fa-user-md"></i>
            </span>
             <h5 class="mt-2">Please Try A Different Username And Password</h5>
            </div>
            <div class="clerafix"></div>
         </div>
      </div>
   </div>
   <!-- authentication error -->
{% endblock %}

hospital/templates/hospital/doctor10.html
{% extends 'hospital/base.html' %}
{% load static %}
{% block body %}
	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'hospital:index' %}">Home</a>
				</li>
				<li class="breadcrumb-item">
                    <a href="{% url 'hospital:about' %}">Team</a>
                   </li>
                <li class="breadcrumb-item active" aria-current="page">Doctor's Profile</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<section class="about py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-left mb-md-5 mb-4">
				<h4 class="title" style="background-color: gainsboro; font-size:40px; padding-top: 1rem; padding-bottom: 1rem; padding-left: 1rem">Dr. Manoj Agny</h4>

			</div>
            <div class="row about_grids mt-5">
                <div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5" >
			</div>
			<div class="row package-grids mt-5" style="margin-top: -4rem !important;">
				<div class="col-md-4">
					<div class="price-top">
                        <img src="../../../media/hospital/Dr-Manoj-Agny-b.jpg" style="height: 300px ; width: 100%; "  alt="">
                    </div>
                </div>
                <div class="col-md-8 my-md-0 my-5">
					<div class="price-top">

              <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Designation:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Senior Consultant Cardiac and Transplant Surgeon
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Department + Services:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Department of Cardio Thoracic Surgery & Heart Transplantion
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Qualification & Fellowship:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">

    MCh., MS., MBBS<br>
    Ex - Faculty (USA)<br>
    Ex - Transplant Fellow (UK)<br>
    <p><a href="{% url 'hospital:appointment' %}" class="w3ls-button-agile" style="color: #00abff">Book Appointment
				</a></p>

              </p> <br>






                    </div>
                    </div>
		</div>
            </div>
                </div>
            </div>
		</div>

    </section>
{% endblock %}

hospital/templates/hospital/doctor12.html
{% extends 'hospital/base.html' %}
{% load static %}
{% block body %}
	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'hospital:index' %}">Home</a>
				</li>
				<li class="breadcrumb-item">
                    <a href="{% url 'hospital:about' %}">Team</a>
                   </li>
                <li class="breadcrumb-item active" aria-current="page">Doctor's Profile</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<section class="about py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-left mb-md-5 mb-4">
				<h4 class="title" style="background-color: gainsboro; font-size:40px; padding-top: 1rem; padding-bottom: 1rem; padding-left: 1rem">Dr. Puneet Chopra</h4>

			</div>
            <div class="row about_grids mt-5">
                <div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5" >
			</div>
			<div class="row package-grids mt-5" style="margin-top: -4rem !important;">
				<div class="col-md-4">
					<div class="price-top">
                        <img src="../../../media/hospital/Dr-Puneet-Chopra-b.JPG" style="height: 300px ; width: 100%; "  alt="">
                    </div>
                </div>
                <div class="col-md-8 my-md-0 my-5">
					<div class="price-top">

              <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Designation:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Consultant
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Department + Services:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Department of Critical Care
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Qualification & Fellowship:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">

    MBBS:GMCH, Sector 32 ,Chandigarh<br>
    IDCCM: Indian Society of Critical Care Medicine<br>
    EDIC: European Society of Critical Care<br>
    <p><a href="{% url 'hospital:appointment' %}" class="w3ls-button-agile" style="color: #00abff">Book Appointment
				</a></p>

              </p> <br>






                    </div>
                    </div>
		</div>
            </div>
                </div>
            </div>
		</div>

    </section>
{% endblock %}

hospital/templates/hospital/doctor2.html
{% extends 'hospital/base.html' %}
{% load static %}
{% block body %}
	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'hospital:index' %}">Home</a>
				</li>
				<li class="breadcrumb-item">
                    <a href="{% url 'hospital:about' %}">Team</a>
                   </li>
                <li class="breadcrumb-item active" aria-current="page">Doctor's Profile</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<section class="about py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-left mb-md-5 mb-4">
				<h4 class="title" style="background-color: gainsboro; font-size:40px; padding-top: 1rem; padding-bottom: 1rem; padding-left: 1rem">Dr. Yugam Aggarwal</h4>

			</div>
            <div class="row about_grids mt-5">
                <div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5" >
			</div>
			<div class="row package-grids mt-5" style="margin-top: -4rem !important;">
				<div class="col-md-4">
					<div class="price-top">
                        <img src="../../../media/hospital/dr.-Yugam_aggarwal-big.jpg" style="height: 300px ; width: 100%; "  alt="">
                    </div>
                </div>
                <div class="col-md-8 my-md-0 my-5">
					<div class="price-top">

              <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Designation:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Consultant
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Department + Services:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Department of Cardiac Anaesthesia
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Qualification & Fellowship:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">

    MBBS, CMC & Hospital, Ludhiana<br>
    MD (Anaesthesia), CMC & Hospital, Ludhiana<br>
    <p><a href="{% url 'hospital:appointment' %}" class="w3ls-button-agile" style="color: #00abff">Book Appointment
				</a></p>

              </p> <br>






                    </div>
                    </div>
		</div>
            </div>
                </div>
            </div>
		</div>

    </section>
{% endblock %}

hospital/templates/hospital/doctor4.html
{% extends 'hospital/base.html' %}
{% load static %}
{% block body %}
	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'hospital:index' %}">Home</a>
				</li>
				<li class="breadcrumb-item">
                    <a href="{% url 'hospital:about' %}">Team</a>
                   </li>
                <li class="breadcrumb-item active" aria-current="page">Doctor's Profile</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<section class="about py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-left mb-md-5 mb-4">
				<h4 class="title" style="background-color: gainsboro; font-size:40px; padding-top: 1rem; padding-bottom: 1rem; padding-left: 1rem">Dr. Kiran Patil</h4>

			</div>
            <div class="row about_grids mt-5">
                <div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5" >
			</div>
			<div class="row package-grids mt-5" style="margin-top: -4rem !important;">
				<div class="col-md-4">
					<div class="price-top">
                        <img src="../../../media/hospital/kiran-patil-sml.jpg" style="height: 300px ; width: 100%; "  alt="">
                    </div>
                </div>
                <div class="col-md-8 my-md-0 my-5">
					<div class="price-top">

              <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Designation:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Senior Consultant
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Department + Services:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">
                 Department of Anaesthesia & Pain Medicine
              </p>

                        <h4 class="aboutpara text-left mx-auto" style="color: orangered">
                  Qualification & Fellowship:
              </h4>
<p class="aboutpara text-left mx-auto" style="color: #1b1e21">

    MBBS, CMC & Hospital, Ludhiana<br>
    MD (Anaesthesia), CMC & Hospital, Ludhiana<br>
                        <br>
    <p><a href="{% url 'hospital:appointment' %}" class="w3ls-button-agile" style="color: #00abff">Book Appointment
				</a></p>

              </p> <br>






                    </div>
                    </div>
		</div>
            </div>
                </div>
            </div>
		</div>

    </section>
{% endblock %}

hospital/templates/hospital/user_welcome.html
{% extends 'hospital/base.html' %}

{% block body %}
   {% if user.is_authenticated %}
    welcome you are successfully login ---- {{ user }} !!!
    {% endif %}
{% endblock %}